"""Render Gate 4 Test Plan IR into Unity NUnit templates."""

from __future__ import annotations

from pathlib import Path
from typing import Dict

from .ir import TestPlanIR


EDITMODE_ASMDEF = """\
{
  "name": "GameTestFixture.EditModeTests",
  "rootNamespace": "GameTestFixture.Tests",
  "references": [
    "GameTestFixture.Runtime"
  ],
  "includePlatforms": [
    "Editor"
  ],
  "excludePlatforms": [],
  "allowUnsafeCode": false,
  "overrideReferences": false,
  "precompiledReferences": [],
  "autoReferenced": false,
  "defineConstraints": [
    "UNITY_INCLUDE_TESTS"
  ],
  "versionDefines": [],
  "noEngineReferences": false,
  "optionalUnityReferences": [
    "TestAssemblies"
  ]
}
"""


EDITMODE_TEST = """\
// <auto-generated>
// Generated by scripts/spec_to_test_smoke.py from Test Plan IR.
// Do not hand-edit; change spec_to_test templates instead.
// </auto-generated>

using GameTestFixture;
using NUnit.Framework;
using UnityEngine;

namespace GameTestFixture.Tests.Generated
{
    public sealed class GeneratedCheckpointRequirementEditModeTest
    {
        [Test]
        [Category("Gate4Generated")]
        public void CheckpointRestorePreservesOpenedDoorState()
        {
            var root = new GameObject("GeneratedCheckpointEditModeFixture");
            try
            {
                var player = AddFixtureComponent<PlayerState>(root, "Player");
                var keycard = AddFixtureComponent<KeycardPickup>(root, "Keycard");
                var checkpoint = AddFixtureComponent<CheckpointMarker>(root, "Checkpoint");
                var doorObject = new GameObject("SecurityDoor");
                doorObject.transform.SetParent(root.transform);
                doorObject.AddComponent<DoorController>();
                var door = doorObject.AddComponent<SecurityDoor>();

                player.MoveTo("keycard_room");
                Assert.IsTrue(keycard.Collect(player));
                player.MoveTo("security_door");
                Assert.IsTrue(door.TryOpen(player));
                Assert.IsTrue(door.IsOpen);
                Assert.IsFalse(player.HasKeycard);

                player.MoveTo("checkpoint_room");
                checkpoint.Capture(player, door, keycard);
                player.MoveTo("hazard_room");
                checkpoint.Restore(player, door, keycard, doorNotPersistedBug: false);

                Assert.IsTrue(door.IsOpen, "checkpoint restore must preserve door_open");
                Assert.AreEqual("checkpoint_room", player.Zone);
                Assert.IsFalse(player.HasKeycard, "consumed keycard remains consumed");
                Assert.IsTrue(keycard.IsCollected, "collected keycard remains collected");
            }
            finally
            {
                Object.DestroyImmediate(root);
            }
        }

        private static T AddFixtureComponent<T>(GameObject root, string name)
            where T : Component
        {
            var gameObject = new GameObject(name);
            gameObject.transform.SetParent(root.transform);
            return gameObject.AddComponent<T>();
        }
    }
}
"""


PLAYMODE_TEST = """\
// <auto-generated>
// Generated by scripts/spec_to_test_smoke.py from Test Plan IR.
// Do not hand-edit; change spec_to_test templates instead.
// </auto-generated>

using System.Collections;
using GameTestFixture;
using NUnit.Framework;
using UnityEngine.TestTools;

namespace GameTestFixture.Tests.Generated
{
    public sealed class GeneratedCheckpointRequirementPlayModeTest
    {
        [UnityTest]
        [Category("Gate4Generated")]
        public IEnumerator CheckpointRespawnAllowsExtractionWithoutSoftlock()
        {
            using (var fixture = new CheckpointRuntimeFixture(doorNotPersistedBug: false))
            {
                fixture.Reset();
                fixture.RunAction("move_to_keycard");
                fixture.RunAction("collect_keycard");
                fixture.RunAction("move_to_door");
                fixture.RunAction("open_door");
                fixture.RunAction("move_to_checkpoint");
                fixture.RunAction("activate_checkpoint");
                fixture.RunAction("move_to_hazard");
                fixture.RunAction("die_and_respawn");
                var finalObservation = fixture.RunAction("extract");
                var debugState = fixture.ExportDebugState();

                Assert.IsTrue(finalObservation.extraction_reached);
                Assert.IsFalse(finalObservation.progression_softlock);
                Assert.IsTrue(debugState.door_open);
                Assert.IsTrue(debugState.extraction_reached);
                Assert.IsFalse(debugState.progression_softlock);
            }

            yield return null;
        }
    }
}
"""


class UnityTestRenderer:
    """Render the supported Gate 4 templates into the Unity fixture project."""

    def __init__(self, unity_project: Path) -> None:
        self.unity_project = unity_project
        self.assets = unity_project / "Assets"
        self.editmode_dir = self.assets / "Tests" / "EditMode"
        self.playmode_dir = self.assets / "Tests" / "PlayMode"

    def render(self, plan: TestPlanIR) -> Dict[str, Path]:
        self._validate_plan(plan)
        self.editmode_dir.mkdir(parents=True, exist_ok=True)
        self.playmode_dir.mkdir(parents=True, exist_ok=True)

        outputs = {
            "editmode_asmdef": self.editmode_dir / "GameTestFixture.EditModeTests.asmdef",
            "editmode_test": self.editmode_dir / "GeneratedCheckpointRequirementEditModeTest.cs",
            "playmode_test": self.playmode_dir / "GeneratedCheckpointRequirementPlayModeTest.cs",
        }
        outputs["editmode_asmdef"].write_text(EDITMODE_ASMDEF, encoding="utf-8")
        outputs["editmode_test"].write_text(EDITMODE_TEST, encoding="utf-8")
        outputs["playmode_test"].write_text(PLAYMODE_TEST, encoding="utf-8")
        return outputs

    @staticmethod
    def _validate_plan(plan: TestPlanIR) -> None:
        templates = {case.template for case in plan.cases}
        required = {
            "checkpoint_state_persistence_unit",
            "checkpoint_respawn_extraction_playmode",
        }
        missing = sorted(required - templates)
        if missing:
            raise ValueError(f"Test Plan IR missing required templates: {', '.join(missing)}")
