"""Render Gate 6 Regression Plan IR into a Unity PlayMode test."""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List

from .ir import RegressionCaseIR, RegressionPlanIR


PLAYMODE_TEMPLATE = """\
// <auto-generated>
// Generated by scripts/bug_to_regression_smoke.py from Regression Test Plan IR.
// Do not hand-edit; change bug_to_regression templates instead.
// </auto-generated>

using System;
using System.Collections;
using GameTestFixture;
using NUnit.Framework;
using UnityEngine.TestTools;

namespace GameTestFixture.Tests.Generated
{{
    public sealed class GeneratedCheckpointSoftlockRegressionTest
    {{
        private const string BugEnvVar = "GATE1_BUG_DOOR_NOT_PERSISTED";

        [UnityTest]
        [Category("Gate6Regression")]
        public IEnumerator CheckpointRespawnExtractionRegressionFromBugReport()
        {{
            bool doorNotPersistedBug = IsEnabled(BugEnvVar);
            using (var fixture = new CheckpointRuntimeFixture(doorNotPersistedBug))
            {{
                fixture.Reset();
{action_lines}
                var finalObservation = fixture.RunAction("extract");
                var debugState = fixture.ExportDebugState();

                Assert.IsTrue(
                    finalObservation.extraction_reached,
                    "Regression from Gate 3: extraction must be reachable after checkpoint respawn. " +
                    $"bug={{doorNotPersistedBug}}; reason={{finalObservation.failure_reason}}");
                Assert.IsFalse(
                    finalObservation.progression_softlock,
                    "Regression from Gate 3: progression_softlock must not recur. " +
                    $"bug={{doorNotPersistedBug}}; reason={{finalObservation.failure_reason}}");
                Assert.IsTrue(debugState.door_open, "debug_state should preserve door_open after respawn.");
                Assert.IsTrue(debugState.extraction_reached, "debug_state should record extraction reached.");
                Assert.IsFalse(debugState.progression_softlock, "debug_state should not report progression_softlock.");
            }}

            yield return null;
        }}

        private static bool IsEnabled(string envVar)
        {{
            return string.Equals(
                Environment.GetEnvironmentVariable(envVar),
                "1",
                StringComparison.OrdinalIgnoreCase);
        }}
    }}
}}
"""


class UnityRegressionRenderer:
    """Render supported Gate 6 regression templates into the Unity fixture."""

    def __init__(self, unity_project: Path) -> None:
        self.unity_project = unity_project
        self.playmode_dir = unity_project / "Assets" / "Tests" / "PlayMode"

    def render(self, plan: RegressionPlanIR) -> Dict[str, Path]:
        case = self._single_supported_case(plan)
        self.playmode_dir.mkdir(parents=True, exist_ok=True)

        output = self.playmode_dir / "GeneratedCheckpointSoftlockRegressionTest.cs"
        output.write_text(self._render_playmode(case), encoding="utf-8")
        return {"playmode_regression_test": output}

    @staticmethod
    def _single_supported_case(plan: RegressionPlanIR) -> RegressionCaseIR:
        if len(plan.cases) != 1:
            raise ValueError("Gate 6 renderer expects exactly one regression case")

        case = plan.cases[0]
        if case.layer != "playmode":
            raise ValueError(f"Gate 6 renderer only supports playmode cases, got {case.layer!r}")
        if case.template != "checkpoint_softlock_regression_playmode":
            raise ValueError(f"unsupported Gate 6 template: {case.template}")
        if "extract" not in case.repro_actions:
            raise ValueError("Gate 6 regression repro actions must include extract")
        return case

    @staticmethod
    def _render_playmode(case: RegressionCaseIR) -> str:
        setup_actions = [action for action in case.repro_actions if action != "extract"]
        action_lines = _render_action_lines(setup_actions)
        return PLAYMODE_TEMPLATE.format(action_lines=action_lines)


def _render_action_lines(actions: List[str]) -> str:
    return "\n".join(f'                fixture.RunAction("{action}");' for action in actions)
