// <auto-generated>
// Generated by scripts/spec_to_test_smoke.py from Test Plan IR.
// Do not hand-edit; change spec_to_test templates instead.
// </auto-generated>

using GameTestFixture;
using NUnit.Framework;
using UnityEngine;

namespace GameTestFixture.Tests.Generated
{
    public sealed class GeneratedCheckpointRequirementEditModeTest
    {
        [Test]
        [Category("Gate4Generated")]
        public void CheckpointRestorePreservesOpenedDoorState()
        {
            var root = new GameObject("GeneratedCheckpointEditModeFixture");
            try
            {
                var player = AddFixtureComponent<PlayerState>(root, "Player");
                var keycard = AddFixtureComponent<KeycardPickup>(root, "Keycard");
                var checkpoint = AddFixtureComponent<CheckpointMarker>(root, "Checkpoint");
                var doorObject = new GameObject("SecurityDoor");
                doorObject.transform.SetParent(root.transform);
                doorObject.AddComponent<DoorController>();
                var door = doorObject.AddComponent<SecurityDoor>();

                player.MoveTo("keycard_room");
                Assert.IsTrue(keycard.Collect(player));
                player.MoveTo("security_door");
                Assert.IsTrue(door.TryOpen(player));
                Assert.IsTrue(door.IsOpen);
                Assert.IsFalse(player.HasKeycard);

                player.MoveTo("checkpoint_room");
                checkpoint.Capture(player, door, keycard);
                player.MoveTo("hazard_room");
                checkpoint.Restore(player, door, keycard, doorNotPersistedBug: false);

                Assert.IsTrue(door.IsOpen, "checkpoint restore must preserve door_open");
                Assert.AreEqual("checkpoint_room", player.Zone);
                Assert.IsFalse(player.HasKeycard, "consumed keycard remains consumed");
                Assert.IsTrue(keycard.IsCollected, "collected keycard remains collected");
            }
            finally
            {
                Object.DestroyImmediate(root);
            }
        }

        private static T AddFixtureComponent<T>(GameObject root, string name)
            where T : Component
        {
            var gameObject = new GameObject(name);
            gameObject.transform.SetParent(root.transform);
            return gameObject.AddComponent<T>();
        }
    }
}
