// <auto-generated>
// Generated by scripts/spec_to_test_smoke.py from Test Plan IR.
// Do not hand-edit; change spec_to_test templates instead.
// </auto-generated>

using System.Collections;
using GameTestFixture;
using NUnit.Framework;
using UnityEngine.TestTools;

namespace GameTestFixture.Tests.Generated
{
    public sealed class GeneratedCheckpointRequirementPlayModeTest
    {
        [UnityTest]
        [Category("Gate4Generated")]
        public IEnumerator CheckpointRespawnAllowsExtractionWithoutSoftlock()
        {
            using (var fixture = new CheckpointRuntimeFixture(doorNotPersistedBug: false))
            {
                fixture.Reset();
                fixture.RunAction("move_to_keycard");
                fixture.RunAction("collect_keycard");
                fixture.RunAction("move_to_door");
                fixture.RunAction("open_door");
                fixture.RunAction("move_to_checkpoint");
                fixture.RunAction("activate_checkpoint");
                fixture.RunAction("move_to_hazard");
                fixture.RunAction("die_and_respawn");
                var finalObservation = fixture.RunAction("extract");
                var debugState = fixture.ExportDebugState();

                Assert.IsTrue(finalObservation.extraction_reached);
                Assert.IsFalse(finalObservation.progression_softlock);
                Assert.IsTrue(debugState.door_open);
                Assert.IsTrue(debugState.extraction_reached);
                Assert.IsFalse(debugState.progression_softlock);
            }

            yield return null;
        }
    }
}
