// <auto-generated>
// Generated by scripts/bug_to_regression_smoke.py from Regression Test Plan IR.
// Do not hand-edit; change bug_to_regression templates instead.
// </auto-generated>

using System;
using System.Collections;
using GameTestFixture;
using NUnit.Framework;
using UnityEngine.TestTools;

namespace GameTestFixture.Tests.Generated
{
    public sealed class GeneratedCheckpointSoftlockRegressionTest
    {
        private const string BugEnvVar = "GATE1_BUG_DOOR_NOT_PERSISTED";

        [UnityTest]
        [Category("Gate6Regression")]
        public IEnumerator CheckpointRespawnExtractionRegressionFromBugReport()
        {
            bool doorNotPersistedBug = IsEnabled(BugEnvVar);
            using (var fixture = new CheckpointRuntimeFixture(doorNotPersistedBug))
            {
                fixture.Reset();
                fixture.RunAction("move_to_keycard");
                fixture.RunAction("collect_keycard");
                fixture.RunAction("move_to_door");
                fixture.RunAction("open_door");
                fixture.RunAction("move_to_checkpoint");
                fixture.RunAction("activate_checkpoint");
                fixture.RunAction("move_to_hazard");
                fixture.RunAction("die_and_respawn");
                var finalObservation = fixture.RunAction("extract");
                var debugState = fixture.ExportDebugState();

                Assert.IsTrue(
                    finalObservation.extraction_reached,
                    "Regression from Gate 3: extraction must be reachable after checkpoint respawn. " +
                    $"bug={doorNotPersistedBug}; reason={finalObservation.failure_reason}");
                Assert.IsFalse(
                    finalObservation.progression_softlock,
                    "Regression from Gate 3: progression_softlock must not recur. " +
                    $"bug={doorNotPersistedBug}; reason={finalObservation.failure_reason}");
                Assert.IsTrue(debugState.door_open, "debug_state should preserve door_open after respawn.");
                Assert.IsTrue(debugState.extraction_reached, "debug_state should record extraction reached.");
                Assert.IsFalse(debugState.progression_softlock, "debug_state should not report progression_softlock.");
            }

            yield return null;
        }

        private static bool IsEnabled(string envVar)
        {
            return string.Equals(
                Environment.GetEnvironmentVariable(envVar),
                "1",
                StringComparison.OrdinalIgnoreCase);
        }
    }
}
