// <auto-generated>
// Generated by scripts/presentation_bug_smoke.py from Gate 7 presentation report.
// Do not hand-edit; change the Gate 7 regression template instead.
// </auto-generated>

using System;
using System.Collections;
using GameTestFixture;
using NUnit.Framework;
using UnityEngine.TestTools;

namespace GameTestFixture.Tests.Generated
{
    public sealed class GeneratedDoorVisualRegressionTest
    {
        private const string VisualBugEnvVar = "GATE7_BUG_DOOR_VISUAL_STUCK_CLOSED";

        [UnityTest]
        [Category("Gate7Regression")]
        public IEnumerator OpenDoorVisualMatchesGameplayStateAfterCheckpointFlow()
        {
            bool doorVisualStuckClosedBug = IsEnabled(VisualBugEnvVar);
            using (var fixture = new CheckpointRuntimeFixture(
                doorNotPersistedBug: false,
                doorVisualStuckClosedBug: doorVisualStuckClosedBug))
            {
                fixture.Reset();
                fixture.RunAction("move_to_keycard");
                fixture.RunAction("collect_keycard");
                fixture.RunAction("move_to_door");
                fixture.RunAction("open_door");
                fixture.RunAction("move_to_checkpoint");
                fixture.RunAction("activate_checkpoint");
                fixture.RunAction("move_to_hazard");
                fixture.RunAction("die_and_respawn");
                var finalObservation = fixture.RunAction("extract");
                var debugState = fixture.ExportDebugState();
                var visualState = fixture.ExportVisualState();

                Assert.IsTrue(
                    finalObservation.extraction_reached,
                    "Gate 7 setup requires extraction to remain reachable.");
                Assert.IsFalse(
                    finalObservation.progression_softlock,
                    "Gate 7 presentation bug must not be a progression_softlock.");
                Assert.IsTrue(debugState.door_open, "Gameplay door state should be open.");
                Assert.IsTrue(debugState.extraction_reached, "debug_state should record extraction reached.");
                Assert.IsFalse(debugState.progression_softlock, "debug_state should not report progression_softlock.");
                Assert.IsTrue(
                    visualState.door_visual_open,
                    "Gate 7 regression: opened door must look open. " +
                    $"bug={doorVisualStuckClosedBug}; visual_color={visualState.door_visual_color}");
            }

            yield return null;
        }

        private static bool IsEnabled(string envVar)
        {
            return string.Equals(
                Environment.GetEnvironmentVariable(envVar),
                "1",
                StringComparison.OrdinalIgnoreCase);
        }
    }
}
