"""Gate 7 presentation/state-visual mismatch smoke.

Runs the checkpoint flow in fixed and visual-bug modes, verifies that gameplay
logic still succeeds while the rendered door state can be wrong, then renders a
Gate7Regression PlayMode test and proves bug build red / fixed build green.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import xml.etree.ElementTree as ET
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Dict, Iterable, List

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from run_unity_tests import DEFAULT_PROJECT, DEFAULT_UNITY_EXE, parse_results, print_log_tail  # noqa: E402
from unity_smoke import (  # noqa: E402
    ACTION_SEQUENCE,
    BridgeClient,
    SmokeFailure,
    assert_png,
    observation,
    run_unity,
    wait_for_ready,
    wait_for_unity,
)


VISUAL_BUG_ENV_VAR = "GATE7_BUG_DOOR_VISUAL_STUCK_CLOSED"
TEST_CATEGORY = "Gate7Regression"

DEFAULT_FIXED_REPORT = REPO_ROOT / "results" / "unity" / "gate7_presentation_fixed_report.json"
DEFAULT_BUG_REPORT = REPO_ROOT / "results" / "unity" / "gate7_presentation_bug_report.json"
DEFAULT_PLAN = REPO_ROOT / "results" / "unity" / "gate7_presentation_regression_plan.json"

DEFAULT_FIXED_RESULTS = REPO_ROOT / "results" / "unity" / "gate7_presentation_fixed_results.xml"
DEFAULT_FIXED_LOG = REPO_ROOT / "results" / "unity" / "gate7_presentation_fixed_unity.log"
DEFAULT_FIXED_READY = REPO_ROOT / "results" / "unity" / "gate7_presentation_fixed_ready.json"

DEFAULT_BUG_RESULTS = REPO_ROOT / "results" / "unity" / "gate7_presentation_bug_results.xml"
DEFAULT_BUG_LOG = REPO_ROOT / "results" / "unity" / "gate7_presentation_bug_unity.log"
DEFAULT_BUG_READY = REPO_ROOT / "results" / "unity" / "gate7_presentation_bug_ready.json"

DEFAULT_REGRESSION_BUG_RESULTS = REPO_ROOT / "results" / "unity" / "gate7_regression_bug_results.xml"
DEFAULT_REGRESSION_BUG_LOG = REPO_ROOT / "results" / "unity" / "gate7_regression_bug_unity.log"
DEFAULT_REGRESSION_FIXED_RESULTS = REPO_ROOT / "results" / "unity" / "gate7_regression_fixed_results.xml"
DEFAULT_REGRESSION_FIXED_LOG = REPO_ROOT / "results" / "unity" / "gate7_regression_fixed_unity.log"

GENERATED_TEST = (
    REPO_ROOT
    / "unity"
    / "GameTestFixture"
    / "Assets"
    / "Tests"
    / "PlayMode"
    / "GeneratedDoorVisualRegressionTest.cs"
)

REGRESSION_TEST_TEMPLATE = """\
// <auto-generated>
// Generated by scripts/presentation_bug_smoke.py from Gate 7 presentation report.
// Do not hand-edit; change the Gate 7 regression template instead.
// </auto-generated>

using System;
using System.Collections;
using GameTestFixture;
using NUnit.Framework;
using UnityEngine.TestTools;

namespace GameTestFixture.Tests.Generated
{{
    public sealed class GeneratedDoorVisualRegressionTest
    {{
        private const string VisualBugEnvVar = "{visual_bug_env_var}";

        [UnityTest]
        [Category("Gate7Regression")]
        public IEnumerator OpenDoorVisualMatchesGameplayStateAfterCheckpointFlow()
        {{
            bool doorVisualStuckClosedBug = IsEnabled(VisualBugEnvVar);
            using (var fixture = new CheckpointRuntimeFixture(
                doorNotPersistedBug: false,
                doorVisualStuckClosedBug: doorVisualStuckClosedBug))
            {{
                fixture.Reset();
{action_lines}
                var finalObservation = fixture.RunAction("extract");
                var debugState = fixture.ExportDebugState();
                var visualState = fixture.ExportVisualState();

                Assert.IsTrue(
                    finalObservation.extraction_reached,
                    "Gate 7 setup requires extraction to remain reachable.");
                Assert.IsFalse(
                    finalObservation.progression_softlock,
                    "Gate 7 presentation bug must not be a progression_softlock.");
                Assert.IsTrue(debugState.door_open, "Gameplay door state should be open.");
                Assert.IsTrue(debugState.extraction_reached, "debug_state should record extraction reached.");
                Assert.IsFalse(debugState.progression_softlock, "debug_state should not report progression_softlock.");
                Assert.IsTrue(
                    visualState.door_visual_open,
                    "Gate 7 regression: opened door must look open. " +
                    $"bug={{doorVisualStuckClosedBug}}; visual_color={{visualState.door_visual_color}}");
            }}

            yield return null;
        }}

        private static bool IsEnabled(string envVar)
        {{
            return string.Equals(
                Environment.GetEnvironmentVariable(envVar),
                "1",
                StringComparison.OrdinalIgnoreCase);
        }}
    }}
}}
"""


class PresentationSmokeFailure(RuntimeError):
    """A machine-checkable Gate 7 assertion failed."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--unity",
        default=os.environ.get("UNITY_EXE", str(DEFAULT_UNITY_EXE)),
        help="Path to Unity.exe. Defaults to UNITY_EXE or the pinned editor.",
    )
    parser.add_argument(
        "--project",
        default=str(DEFAULT_PROJECT),
        help="Unity project path. Defaults to unity/GameTestFixture.",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=90.0,
        help="Seconds to wait for Unity bridge startup and shutdown.",
    )
    return parser.parse_args()


def require(condition: bool, message: str) -> None:
    if not condition:
        raise PresentationSmokeFailure(message)


@contextmanager
def patched_visual_bug_env(enabled: bool) -> Iterable[None]:
    previous = os.environ.get(VISUAL_BUG_ENV_VAR)
    if enabled:
        os.environ[VISUAL_BUG_ENV_VAR] = "1"
    else:
        os.environ.pop(VISUAL_BUG_ENV_VAR, None)

    try:
        yield
    finally:
        if previous is None:
            os.environ.pop(VISUAL_BUG_ENV_VAR, None)
        else:
            os.environ[VISUAL_BUG_ENV_VAR] = previous


def scenario_args(
    args: argparse.Namespace,
    results_path: Path,
    log_path: Path,
    ready_path: Path,
) -> argparse.Namespace:
    return argparse.Namespace(
        unity=args.unity,
        project=args.project,
        results=str(results_path),
        log=str(log_path),
        ready=str(ready_path),
        timeout=args.timeout,
    )


def clean_paths(*paths: Path) -> None:
    for path in paths:
        if path.exists():
            path.unlink()


def drive_and_report(
    args: argparse.Namespace,
    *,
    bug_enabled: bool,
    report_path: Path,
    results_path: Path,
    log_path: Path,
    ready_path: Path,
) -> Dict[str, Any]:
    clean_paths(report_path, results_path, log_path, ready_path)
    process = None
    client: BridgeClient | None = None
    connected = False
    smoke_failed = False

    try:
        with patched_visual_bug_env(bug_enabled):
            process = run_unity(scenario_args(args, results_path, log_path, ready_path))
        host, port = wait_for_ready(process, ready_path, args.timeout)
        print(f"PASS Gate 7 bridge ready {host}:{port}")
        client = BridgeClient(host, port, args.timeout)
        connected = True

        reset = client.request("reset")
        reset_obs = observation(reset)
        require(reset_obs.get("player_zone") == "start", "Reset should start in start zone.")

        final_obs: Dict[str, Any] | None = None
        for action in ACTION_SEQUENCE:
            response = client.request("action", action)
            final_obs = observation(response)
            print(f"PASS Gate 7 action {action}")

        require(final_obs is not None, "Gate 7 action sequence produced no final observation.")

        debug_response = client.request("debug_state")
        debug_state = dict(debug_response.get("debug_state", {}) or {})
        visual_response = client.request("visual_state")
        visual_state = dict(visual_response.get("visual_state", {}) or {})
        screenshot_response = client.request("screenshot")
        screenshot_path = Path(str(screenshot_response.get("screenshot_path", "")))
        assert_png(screenshot_path)
        trace_response = client.request("trace")
        trace = list(trace_response.get("trace", []) or [])

        report = build_report(
            bug_enabled=bug_enabled,
            final_observation=final_obs,
            debug_state=debug_state,
            visual_state=visual_state,
            screenshot_path=screenshot_path,
            trace=trace,
        )
        validate_report(report, expected_bug=bug_enabled)
        write_json(report_path, report)
        print(f"PASS Gate 7 report {report_path}")
    except (PresentationSmokeFailure, SmokeFailure) as exc:
        smoke_failed = True
        print(f"FAIL {exc}")
    except (OSError, json.JSONDecodeError, RuntimeError, ValueError) as exc:
        smoke_failed = True
        print(f"FAIL presentation_smoke_error: {exc}")
    finally:
        if client is not None:
            try:
                client.request("shutdown")
            except (SmokeFailure, OSError, json.JSONDecodeError) as exc:
                smoke_failed = True
                print(f"FAIL bridge_shutdown_error: {exc}")
            finally:
                client.close()

        if process is not None:
            try:
                if connected:
                    unity_exit = wait_for_unity(process, args.timeout, log_path)
                else:
                    if process.poll() is None:
                        process.terminate()
                    unity_exit = wait_for_unity(process, 10.0, log_path)
            except SmokeFailure as exc:
                smoke_failed = True
                unity_exit = -1
                print(f"FAIL {exc}")

            _, unity_failures = parse_results(results_path)
            if unity_exit != 0:
                smoke_failed = True
                print(f"FAIL unity_exit_code={unity_exit}")
                print_log_tail(log_path)
            if unity_failures:
                smoke_failed = True

    if smoke_failed:
        raise PresentationSmokeFailure("Gate 7 presentation scenario failed.")

    return report


def build_report(
    *,
    bug_enabled: bool,
    final_observation: Dict[str, Any],
    debug_state: Dict[str, Any],
    visual_state: Dict[str, Any],
    screenshot_path: Path,
    trace: List[str],
) -> Dict[str, Any]:
    presentation_mismatch = (
        debug_state.get("door_open") is True
        and debug_state.get("extraction_reached") is True
        and debug_state.get("progression_softlock") is False
        and visual_state.get("door_visual_open") is False
    )
    failure_type = "presentation_mismatch" if presentation_mismatch else None
    status = "bug_reported" if failure_type else "success"
    return {
        "status": status,
        "failure_type": failure_type,
        "goal": "Reach extraction and verify the opened door is visually open.",
        "bug_toggle": VISUAL_BUG_ENV_VAR if bug_enabled else None,
        "final_observation": final_observation,
        "debug_state": debug_state,
        "visual_state": visual_state,
        "screenshot_path": str(screenshot_path),
        "trace": trace,
        "visual_evidence": build_visual_evidence(debug_state, visual_state, screenshot_path),
    }


def build_visual_evidence(
    debug_state: Dict[str, Any],
    visual_state: Dict[str, Any],
    screenshot_path: Path,
) -> Dict[str, Any]:
    mismatch = debug_state.get("door_open") is True and visual_state.get("door_visual_open") is False
    return {
        "schema_version": 1,
        "verdict_source": "debug_state+visual_state+trace",
        "visual_evidence_role": "supporting_evidence_only",
        "backend": "fixture-vlm",
        "screenshot_path": str(screenshot_path),
        "questions": [
            {
                "question_id": "door_appears_open",
                "prompt": "Does the security door visually appear open?",
                "answer": "no" if mismatch else "yes",
                "confidence": 0.95,
                "rationale": "The presentation-layer visual_state reports the rendered door state.",
            },
            {
                "question_id": "logic_visual_consistency",
                "prompt": "Is the visible door state consistent with gameplay door_open?",
                "answer": "no" if mismatch else "yes",
                "confidence": 0.94,
                "rationale": "Gameplay door_open and presentation door_visual_open are compared side by side.",
            },
        ],
    }


def validate_report(report: Dict[str, Any], *, expected_bug: bool) -> None:
    debug_state = dict(report.get("debug_state", {}) or {})
    visual_state = dict(report.get("visual_state", {}) or {})
    trace = list(report.get("trace", []) or [])

    require(debug_state.get("door_open") is True, "debug_state.door_open must be true.")
    require(debug_state.get("extraction_reached") is True, "debug_state.extraction_reached must be true.")
    require(
        debug_state.get("progression_softlock") is False,
        "Gate 7 must not report progression_softlock.",
    )
    require("action:open_door" in trace, "trace missing action:open_door.")
    require("action:extract" in trace, "trace missing action:extract.")

    if expected_bug:
        require(
            report.get("failure_type") == "presentation_mismatch",
            f"Expected presentation_mismatch, got {report.get('failure_type')}.",
        )
        require(report.get("failure_type") != "progression_softlock", "Gate 7 bug was misclassified as softlock.")
        require(visual_state.get("door_visual_open") is False, "bug visual_state should show door closed.")
        require(report.get("status") == "bug_reported", "bug report should have status bug_reported.")
        print("PASS Gate 7 presentation_mismatch report")
        return

    require(report.get("failure_type") is None, "fixed report should not include failure_type.")
    require(visual_state.get("door_visual_open") is True, "fixed visual_state should show door open.")
    require(report.get("status") == "success", "fixed report should have status success.")
    print("PASS Gate 7 fixed presentation report")


def write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def render_regression_test(plan_path: Path, bug_report: Dict[str, Any]) -> None:
    plan = {
        "plan_id": "gate7_door_visual_regression_plan",
        "source_failure_type": bug_report.get("failure_type"),
        "source_goal": bug_report.get("goal"),
        "cases": [
            {
                "id": "door_visual_matches_open_logic_playmode",
                "layer": "playmode",
                "template": "door_visual_matches_open_logic_playmode",
                "repro_actions": list(ACTION_SEQUENCE),
                "assertions": [
                    "debug_state records door_open true",
                    "debug_state records extraction_reached true",
                    "debug_state records progression_softlock false",
                    "visual_state records door_visual_open true",
                ],
            }
        ],
    }
    write_json(plan_path, plan)
    action_lines = "\n".join(
        f'                fixture.RunAction("{action}");'
        for action in ACTION_SEQUENCE
        if action != "extract"
    )
    GENERATED_TEST.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_TEST.write_text(
        REGRESSION_TEST_TEMPLATE.format(
            visual_bug_env_var=VISUAL_BUG_ENV_VAR,
            action_lines=action_lines,
        ),
        encoding="utf-8",
    )
    text = GENERATED_TEST.read_text(encoding="utf-8")
    require("<auto-generated>" in text, "Gate 7 regression missing generated header.")
    require(TEST_CATEGORY in text, "Gate 7 regression missing category.")
    require(VISUAL_BUG_ENV_VAR in text, "Gate 7 regression missing visual bug env var.")
    print(f"PASS Gate 7 regression_plan_ir {plan_path}")
    print(f"PASS rendered Gate 7 regression {GENERATED_TEST}")


def unity_regression_command(
    args: argparse.Namespace,
    results_path: Path,
    log_path: Path,
) -> List[str]:
    return [
        sys.executable,
        str(REPO_ROOT / "scripts" / "run_unity_tests.py"),
        "--unity",
        str(args.unity),
        "--project",
        str(args.project),
        "--test-platform",
        "PlayMode",
        "--test-category",
        TEST_CATEGORY,
        "--results",
        str(results_path),
        "--log",
        str(log_path),
    ]


def run_regression(
    args: argparse.Namespace,
    results_path: Path,
    log_path: Path,
    *,
    bug_enabled: bool,
) -> subprocess.CompletedProcess[bytes]:
    clean_paths(results_path, log_path)
    env = os.environ.copy()
    if bug_enabled:
        env[VISUAL_BUG_ENV_VAR] = "1"
    else:
        env.pop(VISUAL_BUG_ENV_VAR, None)

    command = unity_regression_command(args, results_path, log_path)
    print(" ".join(command), flush=True)
    return subprocess.run(command, env=env, check=False)


def read_unity_cases(results_path: Path) -> List[Dict[str, str]]:
    if not results_path.exists():
        raise PresentationSmokeFailure(f"results XML missing: {results_path}")

    root = ET.parse(results_path).getroot()
    cases = []
    for case in root.findall(".//test-case"):
        message = case.findtext("./failure/message", default="").strip()
        cases.append(
            {
                "name": case.attrib.get("fullname") or case.attrib.get("name", "<unnamed>"),
                "result": case.attrib.get("result", "Unknown"),
                "message": message,
            }
        )
    return cases


def assert_regression_bug_failed(process: subprocess.CompletedProcess[bytes], results_path: Path) -> None:
    require(process.returncode != 0, "Gate 7 regression should fail when visual bug is enabled.")
    generated = [
        case
        for case in read_unity_cases(results_path)
        if "GeneratedDoorVisualRegressionTest" in case["name"]
    ]
    require(generated, "Gate 7 generated regression test case missing from bug results.")
    require(any(case["result"] == "Failed" for case in generated), f"Gate 7 bug run should fail: {generated}")
    failure_text = " ".join(case["message"] for case in generated).lower()
    require("visual" in failure_text or "door" in failure_text, "Gate 7 failure should mention visual/door.")
    print("PASS Gate 7 generated regression FAILS on visual bug build")


def assert_regression_fixed_passed(process: subprocess.CompletedProcess[bytes], results_path: Path) -> None:
    require(process.returncode == 0, f"Gate 7 regression should pass on fixed build, exit={process.returncode}.")
    generated = [
        case
        for case in read_unity_cases(results_path)
        if "GeneratedDoorVisualRegressionTest" in case["name"]
    ]
    require(generated, "Gate 7 generated regression test case missing from fixed results.")
    require(all(case["result"] == "Passed" for case in generated), f"Gate 7 fixed run should pass: {generated}")
    print("PASS Gate 7 generated regression PASSES on fixed build")


def main() -> int:
    args = parse_args()

    try:
        fixed_report = drive_and_report(
            args,
            bug_enabled=False,
            report_path=DEFAULT_FIXED_REPORT,
            results_path=DEFAULT_FIXED_RESULTS,
            log_path=DEFAULT_FIXED_LOG,
            ready_path=DEFAULT_FIXED_READY,
        )
        require(fixed_report.get("status") == "success", "fixed Gate 7 report should succeed.")

        bug_report = drive_and_report(
            args,
            bug_enabled=True,
            report_path=DEFAULT_BUG_REPORT,
            results_path=DEFAULT_BUG_RESULTS,
            log_path=DEFAULT_BUG_LOG,
            ready_path=DEFAULT_BUG_READY,
        )
        require(bug_report.get("failure_type") == "presentation_mismatch", "bug report should be presentation_mismatch.")

        render_regression_test(DEFAULT_PLAN, bug_report)

        bug_process = run_regression(
            args,
            DEFAULT_REGRESSION_BUG_RESULTS,
            DEFAULT_REGRESSION_BUG_LOG,
            bug_enabled=True,
        )
        assert_regression_bug_failed(bug_process, DEFAULT_REGRESSION_BUG_RESULTS)

        fixed_process = run_regression(
            args,
            DEFAULT_REGRESSION_FIXED_RESULTS,
            DEFAULT_REGRESSION_FIXED_LOG,
            bug_enabled=False,
        )
        assert_regression_fixed_passed(fixed_process, DEFAULT_REGRESSION_FIXED_RESULTS)
    except PresentationSmokeFailure as exc:
        print(f"FAIL {exc}", flush=True)
        return 1
    except (OSError, ET.ParseError, ValueError) as exc:
        print(f"FAIL presentation_bug_smoke_error: {exc}", flush=True)
        return 1

    print("PASS Gate 7 presentation bug smoke passed.", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
