"""Gate 4 Spec-to-Test smoke.

Reads the checkpoint requirement, emits Test Plan IR, renders templated Unity
EditMode + PlayMode tests, and runs them through Unity CLI.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from run_unity_tests import DEFAULT_PROJECT, DEFAULT_UNITY_EXE  # noqa: E402
from spec_to_test import SpecToTestAgent, UnityTestRenderer  # noqa: E402


DEFAULT_REQUIREMENT = REPO_ROOT / "Doc" / "requirements" / "checkpoint-no-softlock.md"
DEFAULT_PLAN = REPO_ROOT / "results" / "unity" / "spec_to_test_plan.json"
DEFAULT_EDITMODE_RESULTS = REPO_ROOT / "results" / "unity" / "spec_editmode_results.xml"
DEFAULT_EDITMODE_LOG = REPO_ROOT / "results" / "unity" / "spec_editmode_unity.log"
DEFAULT_PLAYMODE_RESULTS = REPO_ROOT / "results" / "unity" / "spec_playmode_results.xml"
DEFAULT_PLAYMODE_LOG = REPO_ROOT / "results" / "unity" / "spec_playmode_unity.log"


class SpecToTestSmokeFailure(RuntimeError):
    """A machine-checkable Gate 4 assertion failed."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--requirement",
        default=str(DEFAULT_REQUIREMENT),
        help="Requirement markdown path.",
    )
    parser.add_argument(
        "--unity",
        default=str(DEFAULT_UNITY_EXE),
        help="Path to Unity.exe.",
    )
    parser.add_argument(
        "--project",
        default=str(DEFAULT_PROJECT),
        help="Unity project path.",
    )
    parser.add_argument(
        "--plan",
        default=str(DEFAULT_PLAN),
        help="Output path for Test Plan IR JSON.",
    )
    return parser.parse_args()


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SpecToTestSmokeFailure(message)


def run_command(command: Iterable[str]) -> None:
    command_list = list(command)
    print(" ".join(command_list), flush=True)
    completed = subprocess.run(command_list, check=False)
    if completed.returncode != 0:
        raise SpecToTestSmokeFailure(
            f"command failed with exit code {completed.returncode}: {' '.join(command_list)}"
        )


def validate_plan(plan_dict: dict) -> None:
    cases = plan_dict.get("cases", [])
    layers = {case.get("layer") for case in cases}
    templates = {case.get("template") for case in cases}
    require("unit" in layers, "Test Plan IR must include a unit/component case.")
    require("playmode" in layers, "Test Plan IR must include a PlayMode case.")
    require(
        "checkpoint_state_persistence_unit" in templates,
        "Test Plan IR missing checkpoint_state_persistence_unit template.",
    )
    require(
        "checkpoint_respawn_extraction_playmode" in templates,
        "Test Plan IR missing checkpoint_respawn_extraction_playmode template.",
    )


def validate_rendered_files(paths: dict[str, Path]) -> None:
    for label, path in paths.items():
        require(path.exists(), f"rendered {label} missing: {path}")
        if path.suffix == ".cs":
            text = path.read_text(encoding="utf-8")
            require("<auto-generated>" in text, f"rendered {label} missing generated header")
            require("Gate4Generated" in text, f"rendered {label} missing Gate4Generated category")


def run_generated_unity_tests(args: argparse.Namespace) -> None:
    runner = REPO_ROOT / "scripts" / "run_unity_tests.py"
    run_command(
        [
            sys.executable,
            str(runner),
            "--unity",
            str(args.unity),
            "--project",
            str(args.project),
            "--test-platform",
            "EditMode",
            "--test-category",
            "Gate4Generated",
            "--results",
            str(DEFAULT_EDITMODE_RESULTS),
            "--log",
            str(DEFAULT_EDITMODE_LOG),
        ]
    )
    run_command(
        [
            sys.executable,
            str(runner),
            "--unity",
            str(args.unity),
            "--project",
            str(args.project),
            "--test-platform",
            "PlayMode",
            "--test-category",
            "Gate4Generated",
            "--results",
            str(DEFAULT_PLAYMODE_RESULTS),
            "--log",
            str(DEFAULT_PLAYMODE_LOG),
        ]
    )


def main() -> int:
    args = parse_args()
    requirement_path = Path(args.requirement)
    plan_path = Path(args.plan)

    try:
        require(requirement_path.exists(), f"requirement missing: {requirement_path}")
        requirement = requirement_path.read_text(encoding="utf-8")

        plan = SpecToTestAgent().plan(requirement)
        plan_dict = plan.to_dict()
        validate_plan(plan_dict)
        plan_path.parent.mkdir(parents=True, exist_ok=True)
        plan_path.write_text(json.dumps(plan_dict, indent=2), encoding="utf-8")
        print(f"PASS test_plan_ir {plan_path}", flush=True)

        rendered = UnityTestRenderer(Path(args.project)).render(plan)
        validate_rendered_files(rendered)
        for label, path in rendered.items():
            print(f"PASS rendered {label} {path}", flush=True)

        run_generated_unity_tests(args)
    except SpecToTestSmokeFailure as exc:
        print(f"FAIL {exc}", flush=True)
        return 1
    except (OSError, ValueError) as exc:
        print(f"FAIL spec_to_test_error: {exc}", flush=True)
        return 1

    print("PASS Spec-to-Test smoke passed.", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
